import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <nav className="  md:px-8 lg:px-16 xl:px-32 2xl:64 px-4 bg-white">
            <NavBar />
          </nav>
          <main className="md:px-8 lg:px-16 xl:px-32 2xl:64 px-4 bg-slate-100">
            {children}
          </main>
        </ClerkProvider>
      </body>
    </html>
  );
}
